<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913124541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create holiday table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE holiday (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DC9AB234AA9E377A ON holiday (date)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE holiday');
    }
}
